# Generated by Django 5.1.6 on 2026-01-13 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ocs", "0001_initial"),
        ("patients", "0001_initial"),
        ("treatment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("followup_date", models.DateTimeField(verbose_name="추적 일시")),
                (
                    "followup_type",
                    models.CharField(
                        choices=[
                            ("routine", "정기 추적"),
                            ("symptom_based", "증상 기반"),
                            ("post_treatment", "치료 후 추적"),
                            ("emergency", "응급 내원"),
                        ],
                        default="routine",
                        max_length=20,
                        verbose_name="추적 유형",
                    ),
                ),
                (
                    "clinical_status",
                    models.CharField(
                        choices=[
                            ("stable", "안정"),
                            ("improved", "호전"),
                            ("deteriorated", "악화"),
                            ("recurrence", "재발"),
                            ("progression", "진행"),
                            ("remission", "관해"),
                        ],
                        max_length=20,
                        verbose_name="임상 상태",
                    ),
                ),
                (
                    "symptoms",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="현재 증상 목록",
                        verbose_name="증상",
                    ),
                ),
                (
                    "kps_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Karnofsky Performance Score (0-100)",
                        null=True,
                        verbose_name="KPS 점수",
                    ),
                ),
                (
                    "ecog_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ECOG Performance Status (0-5)",
                        null=True,
                        verbose_name="ECOG 점수",
                    ),
                ),
                (
                    "vitals",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="BP, HR, RR, BT 등",
                        verbose_name="바이탈 사인",
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="체중(kg)",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="경과 기록")),
                (
                    "next_followup_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="다음 추적 예정일"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="followups",
                        to="patients.patient",
                        verbose_name="환자",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_followups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="기록자",
                    ),
                ),
                (
                    "related_ocs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="followups",
                        to="ocs.ocs",
                        verbose_name="관련 OCS",
                    ),
                ),
                (
                    "treatment_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="followups",
                        to="treatment.treatmentplan",
                        verbose_name="치료 계획",
                    ),
                ),
            ],
            options={
                "verbose_name": "경과 추적",
                "verbose_name_plural": "경과 추적 목록",
                "db_table": "followup",
                "ordering": ["-followup_date"],
                "indexes": [
                    models.Index(
                        fields=["patient"], name="followup_patient_c65e0a_idx"
                    ),
                    models.Index(
                        fields=["clinical_status"], name="followup_clinica_ac9ee1_idx"
                    ),
                    models.Index(
                        fields=["followup_date"], name="followup_followu_5821d6_idx"
                    ),
                    models.Index(
                        fields=["followup_type"], name="followup_followu_43081b_idx"
                    ),
                ],
            },
        ),
    ]
