# Generated by Django 5.1.6 on 2026-01-14 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encounters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounter",
            name="attending_doctor",
            field=models.ForeignKey(
                limit_choices_to={"role__code__in": ["DOCTOR", "SYSTEMMANAGER"]},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="encounters_as_doctor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="담당 의사",
            ),
        ),
    ]
