# Generated by Django 5.1.6 on 2026-01-13 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("encounters", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prescription_id",
                    models.CharField(
                        help_text="사용자 친화적 ID (예: rx_0001)",
                        max_length=30,
                        unique=True,
                        verbose_name="처방전 ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "작성 중"),
                            ("ISSUED", "발행됨"),
                            ("DISPENSED", "조제 완료"),
                            ("CANCELLED", "취소됨"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(
                        blank=True,
                        help_text="처방 관련 진단명",
                        null=True,
                        verbose_name="진단명",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="추가 지시사항 또는 메모",
                        null=True,
                        verbose_name="비고",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="발행일시"
                    ),
                ),
                (
                    "dispensed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="조제완료일시"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="취소일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="취소 사유"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions_as_doctor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="처방 의사",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="encounters.encounter",
                        verbose_name="연관 진료",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="patients.patient",
                        verbose_name="환자",
                    ),
                ),
            ],
            options={
                "verbose_name": "처방전",
                "verbose_name_plural": "처방전 목록",
                "db_table": "prescription",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medication_name",
                    models.CharField(max_length=200, verbose_name="약품명"),
                ),
                (
                    "medication_code",
                    models.CharField(
                        blank=True,
                        help_text="약품 식별 코드 (선택)",
                        max_length=50,
                        null=True,
                        verbose_name="약품 코드",
                    ),
                ),
                (
                    "dosage",
                    models.CharField(
                        help_text="예: 500mg, 10ml", max_length=100, verbose_name="용량"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("QD", "1일 1회"),
                            ("BID", "1일 2회"),
                            ("TID", "1일 3회"),
                            ("QID", "1일 4회"),
                            ("PRN", "필요시"),
                            ("QOD", "격일"),
                            ("QW", "주 1회"),
                        ],
                        default="TID",
                        max_length=20,
                        verbose_name="복용 빈도",
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("PO", "경구"),
                            ("IV", "정맥주사"),
                            ("IM", "근육주사"),
                            ("SC", "피하주사"),
                            ("TOPICAL", "외용"),
                            ("INHALATION", "흡입"),
                            ("OTHER", "기타"),
                        ],
                        default="PO",
                        max_length=20,
                        verbose_name="투여 경로",
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(default=7, verbose_name="처방 일수"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="처방 총 수량", verbose_name="총 수량"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="식전/식후, 주의사항 등",
                        null=True,
                        verbose_name="복용 지시",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="prescriptions.prescription",
                        verbose_name="처방전",
                    ),
                ),
            ],
            options={
                "verbose_name": "처방 항목",
                "verbose_name_plural": "처방 항목 목록",
                "db_table": "prescription_item",
                "ordering": ["prescription", "order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["prescription_id"], name="prescriptio_prescri_cefb25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(fields=["status"], name="prescriptio_status_ac9259_idx"),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["patient"], name="prescriptio_patient_f56b20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["doctor"], name="prescriptio_doctor__c65789_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["created_at"], name="prescriptio_created_1cca4e_idx"
            ),
        ),
    ]
