# Generated by Django 5.1.6 on 2026-01-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="고유 식별 코드",
                        max_length=50,
                        unique=True,
                        verbose_name="의약품 코드",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="일반명 또는 상품명",
                        max_length=200,
                        verbose_name="의약품명",
                    ),
                ),
                (
                    "generic_name",
                    models.CharField(
                        blank=True,
                        help_text="성분명",
                        max_length=200,
                        null=True,
                        verbose_name="일반명",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ANALGESIC", "진통제"),
                            ("ANTIBIOTIC", "항생제"),
                            ("ANTIEPILEPTIC", "항경련제"),
                            ("STEROID", "스테로이드"),
                            ("CHEMOTHERAPY", "항암제"),
                            ("ANTIEMETIC", "항구토제"),
                            ("DIURETIC", "이뇨제"),
                            ("ANTICOAGULANT", "항응고제"),
                            ("SEDATIVE", "진정제"),
                            ("OTHER", "기타"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="약품 분류",
                    ),
                ),
                (
                    "default_dosage",
                    models.CharField(
                        help_text="예: 500mg, 10ml",
                        max_length=100,
                        verbose_name="기본 용량",
                    ),
                ),
                (
                    "default_route",
                    models.CharField(
                        choices=[
                            ("PO", "경구"),
                            ("IV", "정맥주사"),
                            ("IM", "근육주사"),
                            ("SC", "피하주사"),
                            ("TOPICAL", "외용"),
                            ("INHALATION", "흡입"),
                            ("OTHER", "기타"),
                        ],
                        default="PO",
                        max_length=20,
                        verbose_name="기본 투여 경로",
                    ),
                ),
                (
                    "default_frequency",
                    models.CharField(
                        default="TID",
                        help_text="QD, BID, TID, QID, PRN 등",
                        max_length=20,
                        verbose_name="기본 복용 빈도",
                    ),
                ),
                (
                    "default_duration_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="기본 처방 일수"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="정",
                        help_text="정, 캡슐, ml, mg 등",
                        max_length=50,
                        verbose_name="단위",
                    ),
                ),
                (
                    "warnings",
                    models.TextField(
                        blank=True,
                        help_text="복용 시 주의사항",
                        null=True,
                        verbose_name="주의사항",
                    ),
                ),
                (
                    "contraindications",
                    models.TextField(
                        blank=True,
                        help_text="투여 금기 사항",
                        null=True,
                        verbose_name="금기사항",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="비활성화 시 처방 목록에서 제외",
                        verbose_name="사용 가능",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "의약품",
                "verbose_name_plural": "의약품 목록",
                "db_table": "medication",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(fields=["code"], name="medication_code_152843_idx"),
                    models.Index(fields=["name"], name="medication_name_418b2b_idx"),
                    models.Index(
                        fields=["category"], name="medication_categor_42fea4_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="medication_is_acti_a78ba9_idx"
                    ),
                ],
            },
        ),
    ]
