# Generated by Django 5.1.6 on 2026-01-14 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0002_medication"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionitem",
            name="medication",
            field=models.ForeignKey(
                blank=True,
                help_text="의약품 마스터에서 선택 (클릭 처방 시)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescription_items",
                to="prescriptions.medication",
                verbose_name="의약품",
            ),
        ),
    ]
