# Generated by Django 5.1.6 on 2026-01-13 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ocs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagingStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("CT", "CT (Computed Tomography)"),
                            ("MRI", "MRI (Magnetic Resonance Imaging)"),
                            ("PET", "PET (Positron Emission Tomography)"),
                            ("X-RAY", "X-Ray"),
                        ],
                        max_length=20,
                        verbose_name="검사 종류",
                    ),
                ),
                (
                    "body_part",
                    models.CharField(
                        default="brain", max_length=100, verbose_name="촬영 부위"
                    ),
                ),
                (
                    "study_uid",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="Study Instance UID",
                    ),
                ),
                (
                    "accession_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Accession Number",
                    ),
                ),
                (
                    "series_count",
                    models.IntegerField(default=0, verbose_name="시리즈 수"),
                ),
                (
                    "instance_count",
                    models.IntegerField(default=0, verbose_name="이미지 수"),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="예약 일시"
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="검사 수행 일시"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                (
                    "ocs",
                    models.OneToOneField(
                        help_text="연결된 OCS 오더 (job_role=RIS)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imaging_study",
                        to="ocs.ocs",
                        verbose_name="OCS 오더",
                    ),
                ),
            ],
            options={
                "verbose_name": "영상 검사 (DICOM)",
                "verbose_name_plural": "영상 검사 목록 (DICOM)",
                "db_table": "imaging_studies",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["ocs"], name="imaging_stu_ocs_id_681f43_idx"),
                    models.Index(
                        fields=["study_uid"], name="imaging_stu_study_u_e67450_idx"
                    ),
                    models.Index(
                        fields=["modality"], name="imaging_stu_modalit_30d44e_idx"
                    ),
                ],
            },
        ),
    ]
