# Generated by Django 5.1.6 on 2026-01-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imaging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagingstudy",
            name="modality",
            field=models.CharField(
                choices=[
                    ("MRI", "MRI (Magnetic Resonance Imaging)"),
                    ("CT", "CT (Computed Tomography)"),
                    ("PET", "PET (Positron Emission Tomography)"),
                ],
                max_length=20,
                verbose_name="검사 종류",
            ),
        ),
    ]
