# Generated by Django 5.1.6 on 2026-01-13 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_inference", "0001_initial"),
        ("encounters", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(
                        help_text="보고서 식별자 (예: rpt_0001)",
                        max_length=30,
                        unique=True,
                        verbose_name="보고서 ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("INITIAL", "초진 보고서"),
                            ("FOLLOWUP", "경과 보고서"),
                            ("DISCHARGE", "퇴원 보고서"),
                            ("FINAL", "최종 보고서"),
                        ],
                        default="FINAL",
                        max_length=20,
                        verbose_name="보고서 유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "작성 중"),
                            ("PENDING_REVIEW", "검토 대기"),
                            ("APPROVED", "승인됨"),
                            ("FINALIZED", "최종 확정"),
                            ("CANCELLED", "취소됨"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "primary_diagnosis",
                    models.CharField(
                        help_text="최종 주 진단명",
                        max_length=500,
                        verbose_name="주 진단명",
                    ),
                ),
                (
                    "secondary_diagnoses",
                    models.JSONField(
                        blank=True, default=list, verbose_name="부 진단명"
                    ),
                ),
                ("diagnosis_date", models.DateField(verbose_name="진단일")),
                (
                    "treatment_summary",
                    models.TextField(
                        blank=True,
                        help_text="시행된 치료 내역 요약",
                        verbose_name="치료 요약",
                    ),
                ),
                (
                    "treatment_plan",
                    models.TextField(blank=True, verbose_name="향후 치료 계획"),
                ),
                (
                    "ai_analysis_summary",
                    models.TextField(
                        blank=True,
                        help_text="AI 추론 결과 요약",
                        verbose_name="AI 분석 요약",
                    ),
                ),
                (
                    "clinical_findings",
                    models.TextField(blank=True, verbose_name="임상 소견"),
                ),
                (
                    "doctor_opinion",
                    models.TextField(blank=True, verbose_name="의사 소견"),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="권고 사항"),
                ),
                (
                    "prognosis",
                    models.TextField(
                        blank=True, help_text="예상 경과", verbose_name="예후"
                    ),
                ),
                (
                    "author_department",
                    models.CharField(
                        blank=True,
                        help_text="보고서 작성 시점의 작성자 부서",
                        max_length=100,
                        verbose_name="작성자 부서",
                    ),
                ),
                (
                    "author_work_station",
                    models.CharField(
                        blank=True,
                        help_text="보고서 작성 시점의 작성자 근무지",
                        max_length=200,
                        verbose_name="작성자 근무지",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="검토 일시"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="승인 일시"
                    ),
                ),
                (
                    "finalized_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="최종 확정 일시"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                (
                    "ai_inferences",
                    models.ManyToManyField(
                        blank=True,
                        related_name="final_reports",
                        to="ai_inference.aiinference",
                        verbose_name="AI 추론",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="승인자",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="final_reports",
                        to="encounters.encounter",
                        verbose_name="관련 진료",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="final_reports",
                        to="patients.patient",
                        verbose_name="환자",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="검토자",
                    ),
                ),
            ],
            options={
                "verbose_name": "최종 진료 보고서",
                "verbose_name_plural": "최종 진료 보고서 목록",
                "db_table": "final_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "이미지"),
                            ("DOCUMENT", "문서"),
                            ("DICOM", "DICOM 영상"),
                            ("OTHER", "기타"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="파일 유형",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="파일명")),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="파일 경로"),
                ),
                (
                    "file_size",
                    models.IntegerField(default=0, verbose_name="파일 크기 (bytes)"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, verbose_name="설명"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="reports.finalreport",
                        verbose_name="보고서",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="업로드자",
                    ),
                ),
            ],
            options={
                "verbose_name": "보고서 첨부파일",
                "verbose_name_plural": "보고서 첨부파일 목록",
                "db_table": "report_attachment",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "생성"),
                            ("UPDATED", "수정"),
                            ("SUBMITTED", "검토 제출"),
                            ("REVIEWED", "검토 완료"),
                            ("APPROVED", "승인"),
                            ("FINALIZED", "최종 확정"),
                            ("CANCELLED", "취소"),
                        ],
                        max_length=20,
                        verbose_name="동작",
                    ),
                ),
                ("message", models.TextField(verbose_name="로그 메시지")),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="상세 정보"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수행자",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="reports.finalreport",
                        verbose_name="보고서",
                    ),
                ),
            ],
            options={
                "verbose_name": "보고서 로그",
                "verbose_name_plural": "보고서 로그 목록",
                "db_table": "report_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="finalreport",
            index=models.Index(
                fields=["report_id"], name="final_repor_report__69e006_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finalreport",
            index=models.Index(
                fields=["patient"], name="final_repor_patient_b38ba7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finalreport",
            index=models.Index(fields=["status"], name="final_repor_status_347ad4_idx"),
        ),
        migrations.AddIndex(
            model_name="finalreport",
            index=models.Index(
                fields=["created_by"], name="final_repor_created_234def_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finalreport",
            index=models.Index(
                fields=["report_type"], name="final_repor_report__cd7c43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportlog",
            index=models.Index(fields=["report"], name="report_log_report__6c6dab_idx"),
        ),
        migrations.AddIndex(
            model_name="reportlog",
            index=models.Index(fields=["action"], name="report_log_action_81b3a0_idx"),
        ),
        migrations.AddIndex(
            model_name="reportlog",
            index=models.Index(
                fields=["created_at"], name="report_log_created_851c98_idx"
            ),
        ),
    ]
