# Generated by Django 5.1.6 on 2026-01-17 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="설정 키"
                    ),
                ),
                ("value", models.TextField(verbose_name="설정 값 (JSON)")),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="설명"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="수정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "시스템 설정",
                "verbose_name_plural": "시스템 설정",
                "db_table": "system_config",
            },
        ),
    ]
