# Generated by Django 5.1.6 on 2026-01-17 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_system_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitorAlertAcknowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(max_length=50, verbose_name="경고 유형"),
                ),
                ("target_date", models.DateField(verbose_name="대상 날짜")),
                (
                    "acknowledged_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="확인 일시"),
                ),
                ("note", models.TextField(blank=True, verbose_name="메모")),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_acknowledges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="확인자",
                    ),
                ),
            ],
            options={
                "verbose_name": "경고 확인 기록",
                "verbose_name_plural": "경고 확인 기록",
                "db_table": "monitor_alert_acknowledge",
                "unique_together": {("alert_type", "target_date")},
            },
        ),
    ]
