# Generated by Django 5.1.6 on 2026-01-13 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("encounters", "0001_initial"),
        ("ocs", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treatment_type",
                    models.CharField(
                        choices=[
                            ("surgery", "수술"),
                            ("radiation", "방사선 치료"),
                            ("chemotherapy", "항암 치료"),
                            ("observation", "경과 관찰"),
                            ("combined", "병합 치료"),
                        ],
                        max_length=20,
                        verbose_name="치료 유형",
                    ),
                ),
                (
                    "treatment_goal",
                    models.CharField(
                        choices=[
                            ("curative", "완치 목적"),
                            ("palliative", "완화 목적"),
                            ("adjuvant", "보조 요법"),
                            ("neoadjuvant", "선행 요법"),
                        ],
                        default="curative",
                        max_length=20,
                        verbose_name="치료 목표",
                    ),
                ),
                ("plan_summary", models.TextField(verbose_name="치료 계획 요약")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "계획됨"),
                            ("in_progress", "진행 중"),
                            ("completed", "완료"),
                            ("cancelled", "취소됨"),
                            ("on_hold", "보류 중"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="시작 예정일"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료 예정일"),
                ),
                (
                    "actual_start_date",
                    models.DateField(blank=True, null=True, verbose_name="실제 시작일"),
                ),
                (
                    "actual_end_date",
                    models.DateField(blank=True, null=True, verbose_name="실제 종료일"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatment_plans",
                        to="encounters.encounter",
                        verbose_name="진료",
                    ),
                ),
                (
                    "ocs",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatment_plans",
                        to="ocs.ocs",
                        verbose_name="OCS 오더",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatment_plans",
                        to="patients.patient",
                        verbose_name="환자",
                    ),
                ),
                (
                    "planned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planned_treatments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="계획 수립 의사",
                    ),
                ),
            ],
            options={
                "verbose_name": "치료 계획",
                "verbose_name_plural": "치료 계획 목록",
                "db_table": "treatment_plan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_number", models.PositiveIntegerField(verbose_name="회차")),
                ("session_date", models.DateTimeField(verbose_name="치료 일시")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "예정됨"),
                            ("in_progress", "진행 중"),
                            ("completed", "완료"),
                            ("cancelled", "취소됨"),
                            ("missed", "불참"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "session_note",
                    models.TextField(blank=True, verbose_name="치료 기록"),
                ),
                (
                    "adverse_events",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="발생한 부작용 목록",
                        verbose_name="부작용",
                    ),
                ),
                (
                    "vitals_before",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="치료 전 바이탈"
                    ),
                ),
                (
                    "vitals_after",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="치료 후 바이탈"
                    ),
                ),
                (
                    "medications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="투여된 약물 및 용량",
                        verbose_name="투여 약물",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_treatments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="시술 의사",
                    ),
                ),
                (
                    "treatment_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="treatment.treatmentplan",
                        verbose_name="치료 계획",
                    ),
                ),
            ],
            options={
                "verbose_name": "치료 세션",
                "verbose_name_plural": "치료 세션 목록",
                "db_table": "treatment_session",
                "ordering": ["treatment_plan", "session_number"],
            },
        ),
        migrations.AddIndex(
            model_name="treatmentplan",
            index=models.Index(
                fields=["patient"], name="treatment_p_patient_0c69be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="treatmentplan",
            index=models.Index(fields=["status"], name="treatment_p_status_02a44f_idx"),
        ),
        migrations.AddIndex(
            model_name="treatmentplan",
            index=models.Index(
                fields=["treatment_type"], name="treatment_p_treatme_509816_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="treatmentplan",
            index=models.Index(
                fields=["planned_by"], name="treatment_p_planned_ad3ea9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="treatmentsession",
            index=models.Index(
                fields=["treatment_plan"], name="treatment_s_treatme_08fac7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="treatmentsession",
            index=models.Index(fields=["status"], name="treatment_s_status_2d3a2c_idx"),
        ),
        migrations.AddIndex(
            model_name="treatmentsession",
            index=models.Index(
                fields=["session_date"], name="treatment_s_session_1c7835_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="treatmentsession",
            unique_together={("treatment_plan", "session_number")},
        ),
    ]
