# Generated by Django 5.1.6 on 2026-01-13 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("encounters", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OCS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ocs_id",
                    models.CharField(
                        help_text="사용자 친화적 ID (예: ocs_0001)",
                        max_length=20,
                        unique=True,
                        verbose_name="OCS ID",
                    ),
                ),
                (
                    "ocs_status",
                    models.CharField(
                        choices=[
                            ("ORDERED", "오더 생성"),
                            ("ACCEPTED", "접수 완료"),
                            ("IN_PROGRESS", "진행 중"),
                            ("RESULT_READY", "결과 대기"),
                            ("CONFIRMED", "확정 완료"),
                            ("CANCELLED", "취소됨"),
                        ],
                        default="ORDERED",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "job_role",
                    models.CharField(
                        help_text="RIS, LIS, TREATMENT, CONSULT 등",
                        max_length=20,
                        verbose_name="작업 역할",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        help_text="RIS: MRI/CT/PET/X-RAY, LIS: BLOOD/GENETIC/PROTEIN/URINE/CSF/BIOPSY, TREATMENT: SURGERY/RADIATION/CHEMOTHERAPY",
                        max_length=50,
                        verbose_name="작업 유형",
                    ),
                ),
                (
                    "doctor_request",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="의사가 작성한 요청 내용 (JSON)",
                        verbose_name="의사 요청",
                    ),
                ),
                (
                    "worker_result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="작업자가 작성한 결과 (JSON, job_role별 템플릿)",
                        verbose_name="작업 결과",
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="첨부파일 정보 (JSON)",
                        verbose_name="첨부파일",
                    ),
                ),
                (
                    "ocs_result",
                    models.BooleanField(
                        blank=True,
                        help_text="True: 정상/완료, False: 비정상/미완료, None: 미확정",
                        null=True,
                        verbose_name="OCS 결과",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="접수일시"
                    ),
                ),
                (
                    "in_progress_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="진행시작일시"
                    ),
                ),
                (
                    "result_ready_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="결과대기일시"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="확정일시"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="취소일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="최종수정일시"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("urgent", "긴급"), ("normal", "일반")],
                        default="normal",
                        max_length=20,
                        verbose_name="우선순위",
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="취소 사유"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocs_orders_as_doctor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="처방 의사",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocs_orders",
                        to="encounters.encounter",
                        verbose_name="연관 진료",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocs_orders",
                        to="patients.patient",
                        verbose_name="환자",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        help_text="작업 수락 시 배정됨, 취소 시 null",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocs_orders_as_worker",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작업자",
                    ),
                ),
            ],
            options={
                "verbose_name": "OCS",
                "verbose_name_plural": "OCS 목록",
                "db_table": "ocs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OCSHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "OCS 생성"),
                            ("ACCEPTED", "오더 접수"),
                            ("CANCELLED", "작업 취소"),
                            ("STARTED", "작업 시작"),
                            ("RESULT_SAVED", "결과 임시저장"),
                            ("SUBMITTED", "결과 제출"),
                            ("CONFIRMED", "의사 확정"),
                            ("WORKER_CHANGED", "작업자 변경"),
                        ],
                        max_length=20,
                        verbose_name="액션",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="이전 상태"
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="변경된 상태"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="취소/변경 사유",
                        max_length=200,
                        null=True,
                        verbose_name="사유",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="변경 시점"),
                ),
                (
                    "snapshot_json",
                    models.JSONField(
                        blank=True,
                        help_text="변경 시점의 OCS 데이터 스냅샷",
                        null=True,
                        verbose_name="변경 시점 데이터",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="접속 IP"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocs_history_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="변경자",
                    ),
                ),
                (
                    "from_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocs_history_from_worker",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="이전 작업자",
                    ),
                ),
                (
                    "ocs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="ocs.ocs",
                        verbose_name="OCS",
                    ),
                ),
                (
                    "to_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocs_history_to_worker",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="변경된 작업자",
                    ),
                ),
            ],
            options={
                "verbose_name": "OCS 이력",
                "verbose_name_plural": "OCS 이력 목록",
                "db_table": "ocs_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ocs",
            index=models.Index(fields=["ocs_id"], name="ocs_ocs_id_dbf3f8_idx"),
        ),
        migrations.AddIndex(
            model_name="ocs",
            index=models.Index(fields=["ocs_status"], name="ocs_ocs_sta_929200_idx"),
        ),
        migrations.AddIndex(
            model_name="ocs",
            index=models.Index(fields=["job_role"], name="ocs_job_rol_8b62cd_idx"),
        ),
        migrations.AddIndex(
            model_name="ocs",
            index=models.Index(fields=["patient"], name="ocs_patient_5de23a_idx"),
        ),
        migrations.AddIndex(
            model_name="ocs",
            index=models.Index(fields=["doctor"], name="ocs_doctor__501431_idx"),
        ),
        migrations.AddIndex(
            model_name="ocs",
            index=models.Index(fields=["worker"], name="ocs_worker__9ab691_idx"),
        ),
        migrations.AddIndex(
            model_name="ocs",
            index=models.Index(fields=["priority"], name="ocs_priorit_4919bb_idx"),
        ),
        migrations.AddIndex(
            model_name="ocs",
            index=models.Index(fields=["created_at"], name="ocs_created_eb6390_idx"),
        ),
        migrations.AddIndex(
            model_name="ocs",
            index=models.Index(
                fields=["job_role", "-created_at"], name="ocs_jobrole_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ocs",
            index=models.Index(
                fields=["is_deleted", "job_role", "-created_at"],
                name="ocs_deleted_jobrole_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ocshistory",
            index=models.Index(fields=["ocs"], name="ocs_history_ocs_id_cbf8ce_idx"),
        ),
        migrations.AddIndex(
            model_name="ocshistory",
            index=models.Index(fields=["action"], name="ocs_history_action_ddefd5_idx"),
        ),
        migrations.AddIndex(
            model_name="ocshistory",
            index=models.Index(fields=["actor"], name="ocs_history_actor_i_c2e965_idx"),
        ),
        migrations.AddIndex(
            model_name="ocshistory",
            index=models.Index(
                fields=["created_at"], name="ocs_history_created_cd5d32_idx"
            ),
        ),
    ]
