# Generated by Django 5.1.6 on 2026-01-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocs",
            name="job_type",
            field=models.CharField(
                help_text="RIS: MRI/CT/PET, LIS: CBC/CMP/Coagulation/Tumor Markers/GENE_PANEL/RNA_SEQ/DNA_SEQ/BIOMARKER, TREATMENT: SURGERY/RADIATION/CHEMOTHERAPY",
                max_length=50,
                verbose_name="작업 유형",
            ),
        ),
    ]
