# Generated by Django 5.1.6 on 2026-01-15 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_inference", "0002_alter_aiinference_requested_by"),
        ("ocs", "0002_alter_ocs_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocs",
            name="ai_completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="AI 완료 일시"
            ),
        ),
        migrations.AddField(
            model_name="ocs",
            name="ai_inference",
            field=models.ForeignKey(
                blank=True,
                help_text="연결된 AI 추론 결과",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_ocs",
                to="ai_inference.aiinference",
                verbose_name="AI 추론",
            ),
        ),
        migrations.AddField(
            model_name="ocs",
            name="ai_requested_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="AI 요청 일시"
            ),
        ),
        migrations.AddField(
            model_name="ocs",
            name="ai_status",
            field=models.CharField(
                choices=[
                    ("NONE", "미요청"),
                    ("PENDING", "대기 중"),
                    ("PROCESSING", "분석 중"),
                    ("COMPLETED", "분석 완료"),
                    ("FAILED", "분석 실패"),
                ],
                default="NONE",
                help_text="AI 분석 요청/진행/완료 상태",
                max_length=20,
                verbose_name="AI 분석 상태",
            ),
        ),
    ]
