# Generated by Django 5.1.6 on 2026-01-13 07:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_number",
                    models.CharField(
                        help_text="자동 생성됨 (예: P2026010001)",
                        max_length=20,
                        unique=True,
                        verbose_name="환자번호",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("birth_date", models.DateField(verbose_name="생년월일")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "남성"), ("F", "여성"), ("O", "기타")],
                        max_length=1,
                        verbose_name="성별",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="전화번호 형식: 010-1234-5678",
                                regex="^\\d{2,3}-\\d{3,4}-\\d{4}$",
                            )
                        ],
                        verbose_name="전화번호",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="이메일"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="주소")),
                (
                    "ssn",
                    models.CharField(
                        help_text="암호화되어 저장됨",
                        max_length=255,
                        unique=True,
                        verbose_name="주민등록번호",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="혈액형",
                    ),
                ),
                (
                    "allergies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["페니실린", "조영제"] 형식',
                        verbose_name="알레르기",
                    ),
                ),
                (
                    "chronic_diseases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["고혈압", "당뇨"] 형식',
                        verbose_name="기저질환",
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(blank=True, null=True, verbose_name="주 호소"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "활성"),
                            ("inactive", "비활성"),
                            ("deceased", "사망"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제여부"),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_patients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="환자 계정",
                    ),
                ),
            ],
            options={
                "verbose_name": "환자",
                "verbose_name_plural": "환자 목록",
                "db_table": "patients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("ALLERGY", "알레르기"),
                            ("CONTRAINDICATION", "금기사항"),
                            ("PRECAUTION", "주의사항"),
                            ("OTHER", "기타"),
                        ],
                        max_length=20,
                        verbose_name="주의사항 유형",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("HIGH", "높음"), ("MEDIUM", "중간"), ("LOW", "낮음")],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="심각도",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="상세 설명")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="patients.patient",
                        verbose_name="환자",
                    ),
                ),
            ],
            options={
                "verbose_name": "환자 주의사항",
                "verbose_name_plural": "환자 주의사항 목록",
                "db_table": "patient_alerts",
                "ordering": ["-severity", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["patient_number"], name="patients_patient_dd5a30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["name"], name="patients_name_2f3b76_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["phone"], name="patients_phone_ef6690_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["status"], name="patients_status_7c14f6_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["-created_at"], name="patients_created_d307a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientalert",
            index=models.Index(
                fields=["patient", "alert_type"], name="patient_ale_patient_afad6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientalert",
            index=models.Index(
                fields=["patient", "is_active"], name="patient_ale_patient_971ad1_idx"
            ),
        ),
    ]
