# Generated by Django 5.1.6 on 2026-01-14 01:39

from django.conf import settings
from django.db import migrations, models


def migrate_inactive_to_discharged(apps, schema_editor):
    """기존 'inactive' 상태를 'discharged'로 변환"""
    Patient = apps.get_model('patients', 'Patient')
    Patient.objects.filter(status='inactive').update(status='discharged')


def reverse_migrate_status(apps, schema_editor):
    """롤백: 'discharged'를 'inactive'로 복원"""
    Patient = apps.get_model('patients', 'Patient')
    Patient.objects.filter(status='discharged').update(status='inactive')


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. severity 필드 추가
        migrations.AddField(
            model_name="patient",
            name="severity",
            field=models.CharField(
                choices=[
                    ("normal", "정상"),
                    ("mild", "경증"),
                    ("moderate", "중등도"),
                    ("severe", "중증"),
                    ("critical", "위중"),
                ],
                default="normal",
                max_length=10,
                verbose_name="중증도",
            ),
        ),
        # 2. status 필드 변경 (max_length 확장 먼저)
        migrations.AlterField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "진료중"),
                    ("discharged", "퇴원"),
                    ("transferred", "전원"),
                    ("deceased", "사망"),
                ],
                default="active",
                max_length=15,
                verbose_name="환자상태",
            ),
        ),
        # 3. 기존 데이터 마이그레이션 (inactive → discharged)
        migrations.RunPython(migrate_inactive_to_discharged, reverse_migrate_status),
        # 4. severity 인덱스 추가
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["severity"], name="patients_severit_f708fd_idx"),
        ),
    ]
