# Generated by Django 5.1.6 on 2026-01-19 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_add_severity_update_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="external_institution",
            field=models.ForeignKey(
                blank=True,
                help_text="EXTERNAL 역할 사용자 (기관)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_patients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="외부기관",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_external",
            field=models.BooleanField(default=False, verbose_name="외부환자 여부"),
        ),
    ]
