# Generated by Django 5.2.7 on 2026-01-12 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ocs", "0002_alter_ocs_job_type"),
        ("patients", "0002_add_severity_update_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIInference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        help_text="추론 요청 ID (ai_req_0001)",
                        max_length=30,
                        unique=True,
                        verbose_name="Job ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("M1", "M1 (MRI)"),
                            ("MG", "MG (Genetic)"),
                            ("MM", "MM (Multimodal)"),
                        ],
                        max_length=10,
                        verbose_name="모델 타입",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("PROCESSING", "처리중"),
                            ("COMPLETED", "완료"),
                            ("FAILED", "실패"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("manual", "수동"), ("auto", "자동")],
                        default="manual",
                        max_length=10,
                        verbose_name="모드",
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON 형태의 추론 결과",
                        verbose_name="추론 결과",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="에러 메시지"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료일시"
                    ),
                ),
                (
                    "mri_ocs",
                    models.ForeignKey(
                        blank=True,
                        help_text="M1, MM 모델용",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mri_inferences",
                        to="ocs.ocs",
                        verbose_name="MRI OCS",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_inferences",
                        to="patients.patient",
                        verbose_name="환자",
                    ),
                ),
                (
                    "protein_ocs",
                    models.ForeignKey(
                        blank=True,
                        help_text="MM 모델용",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="protein_inferences",
                        to="ocs.ocs",
                        verbose_name="Protein OCS",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_inferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="요청자",
                    ),
                ),
                (
                    "rna_ocs",
                    models.ForeignKey(
                        blank=True,
                        help_text="MG, MM 모델용",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rna_inferences",
                        to="ocs.ocs",
                        verbose_name="RNA OCS",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 추론",
                "verbose_name_plural": "AI 추론 목록",
                "db_table": "ai_inference",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["job_id"], name="ai_inferenc_job_id_fc688e_idx"
                    ),
                    models.Index(
                        fields=["model_type"], name="ai_inferenc_model_t_9db5d1_idx"
                    ),
                    models.Index(
                        fields=["status"], name="ai_inferenc_status_76567d_idx"
                    ),
                    models.Index(
                        fields=["mri_ocs"], name="ai_inferenc_mri_ocs_f14f5e_idx"
                    ),
                    models.Index(
                        fields=["rna_ocs"], name="ai_inferenc_rna_ocs_8bf4b4_idx"
                    ),
                    models.Index(
                        fields=["protein_ocs"], name="ai_inferenc_protein_1a36db_idx"
                    ),
                ],
            },
        ),
    ]
