# Generated by Django 5.1.6 on 2026-01-13 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="일정 제목")),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("meeting", "회의"),
                            ("leave", "휴가"),
                            ("training", "교육"),
                            ("personal", "개인"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="일정 유형",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="설명"),
                ),
                ("start_datetime", models.DateTimeField(verbose_name="시작 일시")),
                ("end_datetime", models.DateTimeField(verbose_name="종료 일시")),
                (
                    "all_day",
                    models.BooleanField(default=False, verbose_name="종일 여부"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="HEX 코드 (예: #5b8def). 비워두면 일정 유형별 기본 색상 사용",
                        max_length=7,
                        verbose_name="색상",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="의사",
                    ),
                ),
            ],
            options={
                "verbose_name": "의사 일정",
                "verbose_name_plural": "의사 일정 목록",
                "db_table": "doctor_schedules",
                "ordering": ["start_datetime"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "start_datetime"],
                        name="doctor_sche_doctor__fb08f6_idx",
                    ),
                    models.Index(
                        fields=["doctor", "-start_datetime"],
                        name="doctor_sche_doctor__6af15a_idx",
                    ),
                    models.Index(
                        fields=["schedule_type"], name="doctor_sche_schedul_408be9_idx"
                    ),
                ],
            },
        ),
    ]
