# Generated by Django 5.1.6 on 2026-01-14 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="일정 제목")),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("meeting", "회의"),
                            ("leave", "휴가"),
                            ("training", "교육"),
                            ("personal", "개인"),
                            ("announcement", "공지"),
                            ("event", "행사"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="일정 유형",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="설명"),
                ),
                ("start_datetime", models.DateTimeField(verbose_name="시작 일시")),
                ("end_datetime", models.DateTimeField(verbose_name="종료 일시")),
                (
                    "all_day",
                    models.BooleanField(default=False, verbose_name="종일 여부"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="HEX 코드 (예: #5b8def). 비워두면 일정 유형별 기본 색상 사용",
                        max_length=7,
                        verbose_name="색상",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="소유자",
                    ),
                ),
            ],
            options={
                "verbose_name": "개인 일정",
                "verbose_name_plural": "개인 일정 목록",
                "db_table": "personal_schedules",
                "ordering": ["start_datetime"],
                "indexes": [
                    models.Index(
                        fields=["user", "start_datetime"],
                        name="personal_sc_user_id_f776c2_idx",
                    ),
                    models.Index(
                        fields=["user", "-start_datetime"],
                        name="personal_sc_user_id_d88138_idx",
                    ),
                    models.Index(
                        fields=["schedule_type"], name="personal_sc_schedul_8ed31e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SharedSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="일정 제목")),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("meeting", "회의"),
                            ("leave", "휴가"),
                            ("training", "교육"),
                            ("personal", "개인"),
                            ("announcement", "공지"),
                            ("event", "행사"),
                            ("other", "기타"),
                        ],
                        default="announcement",
                        max_length=20,
                        verbose_name="일정 유형",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="설명"),
                ),
                ("start_datetime", models.DateTimeField(verbose_name="시작 일시")),
                ("end_datetime", models.DateTimeField(verbose_name="종료 일시")),
                (
                    "all_day",
                    models.BooleanField(default=False, verbose_name="종일 여부"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="HEX 코드 (예: #5b8def). 비워두면 일정 유형별 기본 색상 사용",
                        max_length=7,
                        verbose_name="색상",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("ALL", "전체"),
                            ("ADMIN", "관리자"),
                            ("DOCTOR", "의사"),
                            ("NURSE", "간호사"),
                            ("LIS", "검사실"),
                            ("RIS", "영상실"),
                            ("PATIENT", "환자"),
                            ("EXTERNAL", "외부기관"),
                        ],
                        default="ALL",
                        max_length=20,
                        verbose_name="표시 대상",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="삭제 여부"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shared_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "공유 일정",
                "verbose_name_plural": "공유 일정 목록",
                "db_table": "shared_schedules",
                "ordering": ["start_datetime"],
                "indexes": [
                    models.Index(
                        fields=["visibility", "start_datetime"],
                        name="shared_sche_visibil_25c756_idx",
                    ),
                    models.Index(
                        fields=["start_datetime"], name="shared_sche_start_d_268612_idx"
                    ),
                    models.Index(
                        fields=["schedule_type"], name="shared_sche_schedul_377ee6_idx"
                    ),
                ],
            },
        ),
    ]
