# Generated by Django 5.1.6 on 2026-01-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelTable(
            name="auditlog",
            table="audit_log",
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_role",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("request_method", models.CharField(max_length=10)),
                ("request_path", models.CharField(max_length=500)),
                ("request_params", models.JSONField(blank=True, null=True)),
                (
                    "menu_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("VIEW", "조회"),
                            ("CREATE", "생성"),
                            ("UPDATE", "수정"),
                            ("DELETE", "삭제"),
                            ("EXPORT", "내보내기"),
                            ("PRINT", "인쇄"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        choices=[("SUCCESS", "성공"), ("FAIL", "실패")],
                        default="SUCCESS",
                        max_length=10,
                    ),
                ),
                ("fail_reason", models.TextField(blank=True, null=True)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "access_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["-created_at"], name="access_log_created_7f8c3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["user", "-created_at"], name="access_log_user_id_de9b12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(fields=["action"], name="access_log_action_89e4f0_idx"),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(fields=["result"], name="access_log_result_2d68e1_idx"),
        ),
        migrations.AddIndex(
            model_name="accesslog",
            index=models.Index(
                fields=["ip_address"], name="access_log_ip_addr_c29f4a_idx"
            ),
        ),
    ]
