# Generated by Django 5.1.6 on 2026-01-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_accesslog_alter_auditlog_options_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="accesslog",
            new_name="access_log_created_dbd172_idx",
            old_name="access_log_created_7f8c3e_idx",
        ),
        migrations.RenameIndex(
            model_name="accesslog",
            new_name="access_log_user_id_fdeeb4_idx",
            old_name="access_log_user_id_de9b12_idx",
        ),
        migrations.RenameIndex(
            model_name="accesslog",
            new_name="access_log_action_897514_idx",
            old_name="access_log_action_89e4f0_idx",
        ),
        migrations.RenameIndex(
            model_name="accesslog",
            new_name="access_log_result_755d08_idx",
            old_name="access_log_result_2d68e1_idx",
        ),
        migrations.RenameIndex(
            model_name="accesslog",
            new_name="access_log_ip_addr_b7cb01_idx",
            old_name="access_log_ip_addr_c29f4a_idx",
        ),
    ]
